FROM debian:stretch-backports

ARG DEBIAN_FRONTEND=noninteractive

# Install Ansible
RUN apt update && \
  apt dist-upgrade -o Dpkg::Options::="--force-confnew" -y && \
  apt install -o Dpkg::Options::="--force-confnew" -y software-properties-common git ansible systemd && \
  rm -rf /var/lib/apt/lists/*

# Install Ansible inventory file
RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
