FROM debian:buster-backports

# Install Ansible
RUN apt-get update && \
  apt-get install -y software-properties-common git ansible systemd && \
  rm -rf /var/lib/apt/lists/*

# Install Ansible inventory file
RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
