FROM ubuntu:bionic

ARG DEBIAN_FRONTEND=noninteractive

  # apt dist-upgrade -o Dpkg::Options::="--force-confnew" -y && \
RUN apt update && \
  apt install -y software-properties-common && \

RUN apt-add-repository --yes --update ppa:ansible/ansible && \
  apt install -y ansible && \
  rm -rf /var/lib/apt/lists/*

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# ENTRYPOINT ["/bin/systemd"]
