FROM ubuntu:bionic

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && \
  apt install -y software-properties-common systemd

RUN apt-add-repository --yes --update ppa:ansible/ansible && \
  apt install -y ansible

RUN echo "[local]\nlocalhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
