FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && \
  apt install -y ansible systemd

# TODO: not available for `focal` at https://launchpad.net/~ansible/+archive/ubuntu/ansible - 2020-06-07
# RUN apt-add-repository --yes --update ppa:ansible/ansible && \
#   apt install -y ansible

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
