FROM ubuntu:bionic

RUN apt update && \
  apt dist-upgrade -y && \
  apt install -y software-properties-common systemd && \
  rm -rf /var/lib/apt/lists/*

RUN apt-add-repository --yes --update ppa:ansible/ansible && \
  apt install -y ansible && \
  rm -rf /var/lib/apt/lists/*

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
