FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

  # apt dist-upgrade -o Dpkg::Options::="--force-confnew" -y && \
RUN apt update && \
  apt install -y software-properties-common git systemd ansible && \
  rm -rf /var/lib/apt/lists/*

# TODO: not available for `focal` at https://launchpad.net/~ansible/+archive/ubuntu/ansible - 2020-06-07
# RUN apt-add-repository --yes --update ppa:ansible/ansible && \
#   apt install -y ansible && \
#   rm -rf /var/lib/apt/lists/*

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
